
CREATE TABLE INDICADOR (
	CODIGO_IN serial NOT NULL,
	COD_GENERADO_IN varchar(50)  NULL,
	NOMBRE_IN varchar(255)  NULL,
	DEFINICION_IN varchar(2000)  NULL,
	FUENTE_IN varchar(100)  NULL,
	UNIDAD_MEDIDA_IN varchar(255)  NULL,
	ESTADO_IN varchar(1)  NULL,
	CODIGO_SEC integer null,
	CONSTRAINT INDICADOR_pk PRIMARY KEY (CODIGO_IN)
) WITH (
  OIDS=FALSE
);
	
CREATE TABLE INDICADOR_VALORES (
	CODIGO_IV serial NOT NULL,
	VALOR_IV NUMERIC(10,2)  NULL,
	ANIO_IV INTEGER  NULL,
	CODIGO_PAIS INTEGER  NULL,
	CODIGO_IN INTEGER  NULL,
	ESTADO varchar(1)  NULL,
	CONSTRAINT INDICADOR_VALOR_pk PRIMARY KEY (CODIGO_IV)
) WITH (
  OIDS=FALSE
);

ALTER TABLE INDICADOR ADD CONSTRAINT INDICADOR_SECC_fk0 FOREIGN KEY (CODIGO_SEC) REFERENCES SECCION(CODIGO_SEC);

ALTER TABLE INDICADOR_VALORES ADD CONSTRAINT INDI_VAL_PAIS_fk0 FOREIGN KEY (CODIGO_PAIS) REFERENCES PAIS(CODIGO_PAIS);
ALTER TABLE INDICADOR_VALORES ADD CONSTRAINT INDI_VAL_INDI_fk1 FOREIGN KEY (CODIGO_IN) REFERENCES INDICADOR(CODIGO_IN);

ALTER TABLE SECCION ADD COD_GENERADO VARCHAR(50); 
ALTER TABLE PAIS ADD COD_PAIS VARCHAR(2);