UPDATE SECCION SET NOMBRE_SEC = 'BIODIVERSIDAD Y RECURSOS NATURALES', COD_GENERADO = 'S1' WHERE CODIGO_SEC = 1;
UPDATE SECCION SET NOMBRE_SEC = 'DERECHOS COLECTIVOS, SEGURIDAD SOCIAL, TRABAJADORES', COD_GENERADO = 'S2' WHERE CODIGO_SEC = 2;
UPDATE SECCION SET NOMBRE_SEC = 'ECONÓMICO TRIBUTARIO', COD_GENERADO = 'S3' WHERE CODIGO_SEC = 3;
UPDATE SECCION SET NOMBRE_SEC = 'ESTRUCTURA DEL ESTADO Y ORGANIZACIÓN TERRITORIAL', COD_GENERADO = 'S4' WHERE CODIGO_SEC = 4;
INSERT INTO SECCION (CODIGO_SEC, NOMBRE_SEC, ESTADO_SEC, FECHA_ACT_SEC, COD_GENERADO) VALUES (5, 'FISCALIZACIÓN Y CONTROL POLÍTICO', 'A', CURRENT_DATE, 'S5');
INSERT INTO SECCION (CODIGO_SEC, NOMBRE_SEC, ESTADO_SEC, FECHA_ACT_SEC, COD_GENERADO) VALUES (6, 'JUSTICIA Y SEGURIDAD', 'A', CURRENT_DATE, 'S6');
INSERT INTO SECCION (CODIGO_SEC, NOMBRE_SEC, ESTADO_SEC, FECHA_ACT_SEC, COD_GENERADO) VALUES (7, 'PARTICIPACIÓN CIUDADANA Y CONTROL SOCIAL', 'A', CURRENT_DATE, 'S7');
INSERT INTO SECCION (CODIGO_SEC, NOMBRE_SEC, ESTADO_SEC, FECHA_ACT_SEC, COD_GENERADO) VALUES (8, 'RELACIONES INTERNACIONALES E INTEGRACIÓN', 'A', CURRENT_DATE, 'S8');
INSERT INTO SECCION (CODIGO_SEC, NOMBRE_SEC, ESTADO_SEC, FECHA_ACT_SEC, COD_GENERADO) VALUES (9, 'SALUD, EDUCACIÓN, CULTURA, COMUNICACIÓN', 'A', CURRENT_DATE, 'S9');
INSERT INTO SECCION (CODIGO_SEC, NOMBRE_SEC, ESTADO_SEC, FECHA_ACT_SEC, COD_GENERADO) VALUES (10, 'SOBERANÍA ALIMENTARRIA, SECTOR AGROPECUARIO Y PESQUERO', 'A', CURRENT_DATE, 'S10');


UPDATE PAIS SET COD_PAIS = 'EC' WHERE CODIGO_PAIS = 1;
UPDATE PAIS SET COD_PAIS = 'CL' WHERE CODIGO_PAIS = 2;
INSERT INTO PAIS (CODIGO_PAIS, NOMBRE_PAIS, COD_PAIS) VALUES (3, 'PERÚ', 'PE');
INSERT INTO PAIS (CODIGO_PAIS, NOMBRE_PAIS, COD_PAIS) VALUES (4, 'COLOMBIA', 'CO');


INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 1,'S1.I1','Proporción de la superficie cubierta por bosques','Este indicador corresponde a la proporción de la superficie de bosque respecto de la superficie terrestre total de un país. 
Los bosques se definen como tierras que se extienden por más de 0,5 hectáreas, dotadas de árboles de una altura superior a 5m y una cubierta de copas superior al 10%, o de árboles capaces de alcanzar una altura mínima de 5 metros in situ. Comprende los bosques naturales y las plantaciones forestales, así como los bosques utilizados fundamentalmente con fines de producción, conservación o usos múltiples. No incluye la tierra sometida a un uso predominantemente agrícola o urbano. ','CEPAL','Porcentajes','A',1);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 2,'S1.I2','Superficie de las áreas marinas protegidas','Un área protegida se refiere al área terrestre o marina especialmente dedicada a la protección y mantenimiento de la diversidad biológica, así como de los recursos naturales y culturales asociados, administradas de acuerdo con criterios legales u otro medio eficaz. ','NU
Naciones Unidas','Kilómetros cuadrados','A',1);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 3,'S1.I3','Superficie de las áreas terrestres protegidas','Un área protegida se refiere al área terrestre o marina especialmente dedicada a la protección y mantenimiento de la diversidad biológica, así como de los recursos naturales y culturales asociados, administradas de acuerdo con criterios legales u otro medio eficaz. ','NU
Naciones Unidas','Kilómetros cuadrados','A',1);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 4,'S1.I4','Consumo de sustancias agotadoras de la capa de ozono (SAO)',' Consumo de sustancias que agotan la capa de ozono. Principalmente, sobre el consumo de los tres compuestos químicos más importantes que contribuyen a la destrucción de la capa de ozono, específicamente, clorofluorocarbonos (CFC), hidroclorofluorocarbonos, (HCFC) y bromuro de metilo (metilbromuro). Además se presenta el consumo total que incluye todas las sustancias controladas por el Protocolo de Montreal. Los clorofluorocarbonos (CFCs) son productos químicos inertes, no tóxicos, que se licuan fácilmente. Se emplean en los sistemas de refrigeración, aire acondicionado, envasado y aislamiento o como solventes y  propulsores de aerosoles. Dado que los CFCs no se destruyen en las capas inferiores de la atmósfera se desplazan hacia las capas superiores, donde sus componentes clorados destruyen el ozono. En el protocolo de Montreal, los CFCs corresponden al grupo I del Anexo A, en el que se identifican las siguientes sustancias controladas: CFC-11, CFC-12, CFC-113.
Por su parte, los hidroclorofluorocarbonos (HCFCs) son compuestos generalmente utilizados como sustitutos de los clorofluorocarbonos (CFCs) en los sistemas de refrigeración, debido a que su efecto en el agotamiento de la capa de ozono es menor. 
El bromuro de metilo es una sustancia química compuesta por carbono, hidrógeno y bromo, que se utiliza principalmente como plaguicida agrícola y sustancia fumigadora y que posee un elevado potencial de agotamiento del ozono. 
Las sustancias controladas por el Protocolo de Montreal:
Clorofluorocarbonos (CFCs), Halones,Otros CFCs completamente halogenados,tetracloruro de carbono,tricloroetano (metilcloroformo), Hidroclorofluorocarbonos (HCFCs), Hidrobromofluorocarbonos (HBFCs), Bromoclorometano(HCFCs),
Bromuro de metilo (metilbromuro) ','CEPAL','Toneladas de potencial de agotamiento del ozono (PAO)','A',1);

INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 5,'S2.I5','Tasa de desempleo','Tasa de desempleo tomado el 1er trimestre de cada año de cada paíssobre la base de la información de los países ','CEPAL','Tasa','A',2);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 6,'S2.I6','Contribuciones sociales ','Las contribuciones sociales son ingresos provenientes de empleadores, a nombre de sus empleados, o de empleados, trabajadores por cuenta propia o no empleados, que garantizan el derecho a prestaciones sociales a los contribuyentes, sus dependientes o sus supervivientes. Estas contribuciones pueden ser obligatorias o voluntarias y se clasifican en contribuciones a la seguridad social y otras contribuciones sociales, según el tipo de sistema que las reciba. ','Información Países',' (En porcentajes del producto interno bruto)','A',2);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 7,'S3.I7','Ingresos Tributarios  ','Ingresos tributarios: se definen como contribuciones obligatorias, sin contraprestación, no recuperables, impuestas por el gobierno con fines públicos. Se incluyen en esta categoría las contribuciones al seguro social (pagos obligatorios que efectúanlos asegurados, o sus empleadores, a instituciones gubernamentales que proporcionan prestaciones de bienestar y seguro social. Ingresos tributarios directos: 1.1. Impuestos sobre el ingreso, las utilidades y las ganancias de capital. 1.2. Impuestos sobre la propiedad. 1.3. Otros impuestos directos. 2. Ingresos tributarios indirectos: 2.1. Impuestos generales sobre bienes y servicios. 2.2. Impuestos específicos sobre bienes y servicios. 2.3. Impuestos sobre el comercio y transacciones internacionales. 2.4. Otros impuestos indirectos.
','Información Países',' (En porcentajes del producto interno bruto)','A',3);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 8,'S4.I8','Sueldos y Salarios','Sueldos y salarios: esta categoría incluyen los pagos en efectivo a las empleados a cambio de los servicios prestados y las contribuciones del gobierno en su calidad de empleador','Información Países',' (En porcentajes del producto interno bruto)','A',4);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 9,'S5.I9','Indice de percepciones de corrupción','(Promedio. Escala de 0 a 100, donde 0 = mayor nivel de corrupción y 100 = menor nivel de corrupción)','Transparency International','Promedio','A',5);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 10,'S5.I10','Percepciones de desigualdad y conflicto','Proporción de personas que opinan que la distribución del ingreso en su país es injusta','CEPAL','Porcentaje','A',5);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 11,'S6.I11','Homicidio intencional','Los homicidios intencionales son cálculos de homicidios ilegales cometidos en forma intencional como resultado de conflictos internos, violencia interpersonal, conflictos violentos por la tierra o sus recursos, violencia entre pandillas por el territorio o el control y asesinatos y violencia que atenta contra la integridad física por parte de grupos armados. El homicidio intencional no incluye todos los asesinatos intencionales; la diferencia suele encontrarse en la organización del asesinato','Banco Mundial/Información de Países','Tasa por cada 100 000 ','A',6);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 12,'S6.I12','Delitos sexuales contra niños',' ""todo delito de carácter sexual cometido contra niños [de acuerdo con la edad definida por cada país . Se deben incluyen  delitos de pornografía infantil, proxenetismo de menores, relaciones sexuales con una persona que no ha alcanzado la edad de libre consentimiento y otros delitos relacionados con la explotación sexual de menores"". 
Las tasas son calculadas por 100,000 niños. Algunos países, con menos de 100.000 niños tienen sus tasas calculadas de este modo para efecto de comparación','Observatorio de Segurida OEA','Tasa por cada 100 000 ','A',6);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 13,'S6.I13','Personas Imputadas','" se entiende el número total de presuntos infractores contra quienes en el año objeto de examen se inició una acción penal por el Ministerio Público o el organismo de aplicación de la ley competente a nivel nacional, independientemente de la decisión con que se cerró la causa','Ministerios de Justicia Países','Tasa por cada 100 000 ','A',6);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 14,'S7.I14','confianza en las instituciones políticas y del estado','Se calcula en tres etapas: 1.Se obtiene, para cada persona, el promedio simple de sus respuestas a las preguntas sobre el nivel de confianza en los partidos políticos, el poder legislativo y el poder judicial. 2. Dado que las respuestas para cada una de las instituciones se efectúan en una escala con los siguientes valores: 1) Mucha, 2) Alguna, 3) Poca y 4) Ninguna, se considera que las personas que obtienen promedios simples iguales o mayores a 3, confían poco o nada en las instituciones políticas y del estado. 3. División del total de personas de 18 años y más que confía poco o nada en las instituciones políticas y del estado (numerador) por el total de la población de 18 años y más (denominador). El resultado se multiplica por 100. ','CEPAL','Porcentaje','A',7);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 15,'S8.I15','Población emigrante',' Población emigrante de 15 años en adelante en la OCDE en 2010-2011 por país y región de nacimiento
','OECD','en miles','A',8);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 16,'S8.I16','Población emigrante altamente cualificada',' Población emigrante de 15 años en adelante en la OCDE en 2010-2011 por país y región de nacimiento
','OECD','en miles','A',8);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 17,'S9.I17','Gasto público en educación','Gasto Público en educación como porcentaje del producto nacional bruto: Se calcula dividiendo el gasto público de gobierno en un año financiero determinado (numerador) por el producto nacional bruto total de un país determinado y para ese mismo año (denominador). El resultado se multiplica por 100. Gasto Público en educación como porcentaje del producto interno bruto: Se calcula dividiendo el gasto público de gobierno en un año financiero determinado (numerador) por el producto interno bruto total de un país determinado y para ese mismo año (denominador). El resultado se multiplica por 100.','UNESCO','Porcentaje','A',9);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 18,'S9.I18','Gasto público en salud','Se calcula como el cociente entre el gasto en salud del Gobierno General (numerador), dividido por el monto del producto interno (denominador) multiplicado por 100','OMS','Porcentaje','A',9);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 19,'S9.I19','Hogares con acceso a internet','El porcentaje de hogares que tienen acceso a Internet es una medida del nivel de disponibilidad de esta tecnología en el total de los hogares de un país. Esta medida indica por cada 100 hogares, cuantos disponen de servicio de Internet.','CEPAL','Porcentaje','A',9);
INSERT INTO INDICADOR (CODIGO_IN, COD_GENERADO_IN, NOMBRE_IN, DEFINICION_IN, FUENTE_IN, UNIDAD_MEDIDA_IN, ESTADO_IN, CODIGO_SEC) VALUES ( 20,'S10.I20','Gasto del Gobierno Central en el Sector Agropecuario','La agricultura corresponde a las divisiones 1-5 de la CIIU e incluye la silvicultura, la caza y la pesca, además del cultivo de cosechas y la cría de animales. El valor agregado es la producción neta de un sector después de sumar todos los productos y restar los insumos intermedios. Se calcula sin hacer deducciones por depreciación de bienes manufacturados o por agotamiento y degradación de recursos naturales. El origen del valor agregado de determina a partir de la CIIU, Revisión 3. Nota: Para los países que contabilizan en base valor agregado, se utiliza como denominador el valor agregado bruto al costo de los factores','SIAGRO','Porcentaje','A',10);
